### ISSUE TITLE
Crashing when loading UDFs

### ISSUE THREAD

**Issue by ianjohnson2000** [SIMSBulkImport/SIMSBulkImport#24]
Hi there,

I'm trying to import some staff data (mainly email addresses) using the bulk import tool but it crashes when it it tries to load the UDFs. There is no error message and I can't see anything in event viewer but the application quits at this point.

I've tried it on both Windows 10 and Windows 2012r2. I have used it before with Windows 10. I am importing an Excel file as well.

Windows 10 Pro, version 1511, build 10586.218
SIMS version 7.168 build 50, database version 3.62.377

**Comment by rpwillis** [comment]
Have you looked in the log?

**Comment by ianjohnson2000** [comment]
This is what I've found in the log:

2016-05-08 20:30:49.5833|Debug|Loading UDFs - Staff 
2016-05-08 20:30:49.5833|Trace|Trace:: Matt40k.SIMSBulkImport.PreImport.GetUserType(GET) 
2016-05-08 20:30:49.5908|Trace|Trace:: Matt40k.SIMSBulkImport.ImportFile.GetDataSet(GET) 
2016-05-08 20:30:49.5908|Trace|Trace:: Matt40k.SIMSBulkImport.Match.GetDataTable() 
2016-05-08 20:30:49.6468|Error|System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at Matt40k.SIMSBulkImport.Match.GetDataTable() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\UI\Match.xaml.cs:line 264
   at Matt40k.SIMSBulkImport.Open.bwOpen_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\UI\Open.xaml.cs:line 136
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Matt40k.SIMSBulkImport.Program.Main(String[] args) in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\Program.cs:line 31

**Comment by matt40k** [comment]
Have you tried a CSV file rather then a spreadsheet?

**Comment by ianjohnson2000** [comment]
Just tried it with a CSV and it does work.

**Comment by matt40k** [comment]
OK, so looks like a bug in the Excel reading code - what version of Microsoft Office do you have installed? Also bitness

**Comment by ianjohnson2000** [comment]
Its Office 2016 Pro Plus (16.0.4366.1000).

**Comment by matt40k** [comment]
Completed in 2.4.11 - 42f1a201c5ba1f36beec588a810839390c90c35e
