### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by matt40k** [SIMSBulkImport/SIMSBulkImport#26]
2016-08-03 08:40:09.0429|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at Matt40k.SIMSBulkImport.ConfigMan.ReadConfig() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\ConfigMan.cs:line 68
   at Matt40k.SIMSBulkImport.ConfigMan..ctor() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\ConfigMan.cs:line 44
   at Matt40k.SIMSBulkImport.Login.BeginLoad() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\UI\Login.xaml.cs:line 52
   at Matt40k.SIMSBulkImport.PageSwitcher..ctor() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\PageSwitcher.xaml.cs:line 26
   at Matt40k.SIMSBulkImport.Program.Main(String[] args) in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\Program.cs:line 31

**Comment by matt40k** [comment]
Version: 2.3.33

**Comment by matt40k** [comment]
2016-08-03 08:40:40.2308|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at Matt40k.SIMSBulkImport.ConfigMan.ReadConfig() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\ConfigMan.cs:line 68
   at Matt40k.SIMSBulkImport.ConfigMan..ctor() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\ConfigMan.cs:line 44
   at Matt40k.SIMSBulkImport.Login.BeginLoad() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\UI\Login.xaml.cs:line 52
   at Matt40k.SIMSBulkImport.PageSwitcher..ctor() in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\PageSwitcher.xaml.cs:line 26
   at Matt40k.SIMSBulkImport.Program.Main(String[] args) in s:\TeamCity\buildAgent\work\bc5cd9411c11aeb2\SIMSBulkImport\Program.cs:line 31 
2016-08-03 08:42:04.1531|Debug|Trace:: SIMSBulkImport.Program.Main() 
2016-08-03 08:42:04.3878|Error|System.Windows.Markup.XamlParseException: Initialization of 'SIMSBulkImport.PageSwitcher' threw an exception. ---> System.TypeInitializationException: The type initializer for 'MahApps.Metro.Behaviours.StylizedBehaviors' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at MahApps.Metro.Behaviours.StylizedBehaviors..cctor()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at System.Windows.DependencyProperty.FromName(String name, Type ownerType)
   at System.Windows.Baml2006.Baml2006Reader.WriteTypeConvertedInstance(Int16 converterId, Int32 dataByteSize)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyCustom()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.ReadObject(KeyRecord record)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.SystemResources.LookupResourceInDictionary(ResourceDictionary dictionary, Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at SIMSBulkImport.PageSwitcher..ctor()
   at SIMSBulkImport.Program.Main(String[] args) System.Windows.Markup.XamlParseException: Initialization of 'SIMSBulkImport.PageSwitcher' threw an exception. ---> System.TypeInitializationException: The type initializer for 'MahApps.Metro.Behaviours.StylizedBehaviors' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Interactivity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at MahApps.Metro.Behaviours.StylizedBehaviors..cctor()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at System.Windows.DependencyProperty.FromName(String name, Type ownerType)
   at System.Windows.Baml2006.Baml2006Reader.WriteTypeConvertedInstance(Int16 converterId, Int32 dataByteSize)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyCustom()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.ReadObject(KeyRecord record)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.SystemResources.LookupResourceInDictionary(ResourceDictionary dictionary, Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at SIMSBulkImport.PageSwitcher..ctor()
   at SIMSBulkImport.Program.Main(String[] args)
2016-08-03 08:45:18.4683|Trace|Trace:: Matt40k.SIMSBulkImport.Program.Main()

**Comment by matt40k** [comment]
Completed in 2.4.11 - 42f1a201c5ba1f36beec588a810839390c90c35e
