### ISSUE TITLE
SQL Exception

### ISSUE THREAD

**Issue by matt40k** [SIMSBulkImport/SIMSBulkImport#37]
2016-09-09 17:02:06.0670|Error|System.Data.SqlClient.SqlException (0x80131904): @Uniform_Grant_xml is not a parameter for procedure sta_pix_EditStudentInformation_Save_705.
   at SIMS.Processes.Database.ExecuteNoResult(IDbCommand command, Boolean AsCP320)
   at SIMS.Processes.EditStudentBase.doSave()
   at SIMSBulkImport.Classes.Pupils.SetPupilUDF(Int32 personid, String udfvalue)

**Comment by matt40k** [comment]
SIMS Bulk Import version: 2.4.11.0

**Comment by matt40k** [comment]
Comment from stored procedure:

> /* Modified By: Bhavika Mange																					*/
/* Date       : 02/10/2016													                                    */
/* Comments   : Story 91474 - Removal of uniform grant field from Additional information panel of student		*/

Looks like might be a issue with an old version of SIMS .net

**Comment by matt40k** [comment]
(NB: Capita used American date format - MM/DD/YYYY)
