### ISSUE TITLE
No SIMS .net installed

### ISSUE THREAD

**Issue by matt40k** [SIMSBulkImport/SIMSBulkImport#40]
Could do with a pop up

2016-09-18 08:01:16.1383|Debug|Reading SIMS.ini 
2016-09-18 08:01:16.1383|Debug|Trace:: SIMSBulkImport.Core.SimsIni.GetSimsDir(GET) 
2016-09-18 08:01:16.1383|Debug|Trace:: SIMSBulkImport.Core.SimsIni.curdir(GET) 
2016-09-18 08:01:16.1383|Debug|Trace:: SIMSBulkImport.Core.SimsIni.windir(GET) 
2016-09-18 08:01:16.1519|Fatal|System.Exception: Unable to find SIMS.ini
   at SIMSBulkImport.Core.SimsIni.get_GetSimsDir() System.Exception: Unable to find SIMS.ini
   at SIMSBulkImport.Core.SimsIni.get_GetSimsDir()

**Comment by matt40k** [comment]
Also if the sims.ini exists, but the folder is invalid

2016-09-18 08:04:02.7936|Debug|Reading SIMS.ini 
2016-09-18 08:04:02.7975|Debug|Trace:: SIMSBulkImport.Core.SimsIni.GetSimsDir(GET) 
2016-09-18 08:04:02.7975|Debug|Trace:: SIMSBulkImport.Core.SimsIni.curdir(GET) 
2016-09-18 08:04:02.7975|Debug|Trace:: SIMSBulkImport.Core.SimsIni.windir(GET) 
2016-09-18 08:04:02.7975|Debug|Trace:: SIMSBulkImport.Core.IniFile.IniFile(INIPath: C:\Windows\sims.ini) 
2016-09-18 08:04:02.7975|Debug|Trace:: SIMSBulkImport.Core.IniFile.Read(Section: Setup, Key: SIMSDotNetDirectory) 
2016-09-18 08:04:02.7975|Fatal|System.Exception: SIMS .net Application directory does not exist! - 
   at SIMSBulkImport.Core.SimsIni.get_GetSimsDir() System.Exception: SIMS .net Application directory does not exist! - 
   at SIMSBulkImport.Core.SimsIni.get_GetSimsDir()

**Comment by matt40k** [comment]
Also if the folder exists but doesn't have the sims application

No error occurs, application loads of however when trying to login:
2016-09-18 08:08:10.8689|Error|System.IO.FileNotFoundException: Could not load file or assembly 'Cache, Version=7.153.10.0, Culture=neutral, PublicKeyToken=21f532fe36bf9cd6' or one of its dependencies. The system cannot find the file specified.
File name: 'Cache, Version=7.153.10.0, Culture=neutral, PublicKeyToken=21f532fe36bf9cd6' ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Program Files (x86)\SIMS\SIMS .net\Cache.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Program Files (x86)\SIMS\SIMS .net\Cache.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at SIMSBulkImport.SIMSAPI.currentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at SIMSBulkImport.SIMSAPI.get_Connect()
   at SIMSBulkImport.Login.bw_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

 System.IO.FileNotFoundException: Could not load file or assembly 'Cache, Version=7.153.10.0, Culture=neutral, PublicKeyToken=21f532fe36bf9cd6' or one of its dependencies. The system cannot find the file specified.
File name: 'Cache, Version=7.153.10.0, Culture=neutral, PublicKeyToken=21f532fe36bf9cd6' ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Program Files (x86)\SIMS\SIMS .net\Cache.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Program Files (x86)\SIMS\SIMS .net\Cache.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at SIMSBulkImport.SIMSAPI.currentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at SIMSBulkImport.SIMSAPI.get_Connect()
   at SIMSBulkImport.Login.bw_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by matt40k** [comment]
Duplicate of #36

**Comment by matt40k** [comment]
Resolved in v2.5
