### ISSUE TITLE
Better handling if the file is null

### ISSUE THREAD

**Issue by matt40k** [SIMSBulkImport/SIMSBulkImport#7]
Check the file has at least 2 columns

**Comment by matt40k** [comment]
Error from blank CSV
2016-08-21 00:38:10.7719|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at SIMSBulkImport.Match.Load() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 114
   at SIMSBulkImport.Match..ctor() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 57
   at SIMSBulkImport.Open.bwOpen_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Open.xaml.cs:line 136
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SIMSBulkImport.Program.Main(String[] args) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\Program.cs:line 26 System.NullReferenceException: Object reference not set to an instance of an object.
   at SIMSBulkImport.Match.Load() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 114
   at SIMSBulkImport.Match..ctor() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 57
   at SIMSBulkImport.Open.bwOpen_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Open.xaml.cs:line 136
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SIMSBulkImport.Program.Main(String[] args) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\Program.cs:line 26

**Comment by matt40k** [comment]
Error from blank Excel
2016-08-21 00:37:27.5140|Debug|Trace:: SIMSBulkImport.Match.GetDataTable() 
2016-08-21 00:37:27.5570|Error|System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at SIMSBulkImport.Match.GetDataTable() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 263
   at SIMSBulkImport.Match.Load() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 126
   at SIMSBulkImport.Match..ctor() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 58
   at SIMSBulkImport.Open.bwOpen_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Open.xaml.cs:line 136
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SIMSBulkImport.Program.Main(String[] args) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\Program.cs:line 26 System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at SIMSBulkImport.Match.GetDataTable() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 263
   at SIMSBulkImport.Match.Load() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 126
   at SIMSBulkImport.Match..ctor() in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Match.xaml.cs:line 58
   at SIMSBulkImport.Open.bwOpen_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\UI\Open.xaml.cs:line 136
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SIMSBulkImport.Program.Main(String[] args) in C:\Users\MattSmith\Documents\GitHub\SIMSBulkImport\SIMSBulkImport\Program.cs:line 26

**Comment by matt40k** [comment]
Completed in 2.4.11 - 42f1a201c5ba1f36beec588a810839390c90c35e
